apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quote-api-ingress
spec:
  rules:
  - host: quote.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quote-api-service
            port:
              number: 80

